### ISSUE TITLE
The WhatsApp URL doesn't seem to be getting sent correctly. (stable-3_4_0)

### ISSUE THREAD

**Issue by YvesLepidus** [ojsde/shariff#42]
Testing sharing via WhatsApp, we noticed that the link is not being decoded correctly in the application. It is recommended to use the prefix 'https://api.whatsapp.com/' in the API URL, and this seems to work better. The latest versions of the Shariff [already seem to have fixed this](https://github.com/heiseonline/shariff/blob/v3.3.0/src/js/services/whatsapp.js#L68).
We updated the library to version [v3.3.0](https://github.com/heiseonline/shariff/tree/v3.3.0) and saw that the issue was resolved, so we opened a [PR](https://github.com/ojsde/shariff/pull/38) with this update.

**Comment by ronste** [comment]
Hi @YvesLepidus ,

thanks for pointing this out and, indeed, for doing the update! I wasn't aware of the new version because I always looked for new release packages.

I now also found the npm package: [https://www.npmjs.com/package/shariff?activeTab=readme](https://www.npmjs.com/package/shariff?activeTab=readme)

I will merge your PR and do some testing and update documentation before I update the plugin gallery.
