### ISSUE TITLE
delete text (tweet, share) next to the icons

### ISSUE THREAD

**Issue by davidalar** [ojsde/shariff#6]
Hi!

1.- I need to delete the text (tweet, share) next to the icons. that is, only the icon is displayed, not the text.

2.- Is it possible to change the text, for example, instead of "share" that appears "spread"?
Thanks!

**Comment by lilients** [comment]
Hi @davidalar , the shariff plugin for OJS uses the [shariff solution from heise](https://github.com/heiseonline/shariff). In theory all features that are available for the heise tool can be implemented in the OJS plugin. If you want the buttons to display another language, you only need to change the language of your OJS installation. The OJS plugins reads the chosen language from the OJS GUI and hands it to the plugin. 

![shariff_it](https://user-images.githubusercontent.com/7815226/33653964-f294fa28-da6e-11e7-9ad1-1806603508de.PNG)
![shariff_de](https://user-images.githubusercontent.com/7815226/33653967-f4fd333e-da6e-11e7-9d07-51caff2fc75d.PNG)

Does that solve your problem?

**Comment by dennmuel** [comment]
Hello @davidalar ,

I assume you don't want to just change the language, but manipulate the exact wording (or remove textual hints entirely). So maybe a possible solution would be to edit the contents of `shariff/shariff.complete.js ` and/or `shariff/shariff.min.js` where the respective strings are deposited.

Since I'm not so experienced in coding, my not-so-educated guess is, that these strings look kind of "hard coded". Maybe switching to keys and adding editable locales would be a more elegant solution (--> possible feature request?).

Kind regards
Dennis

**Comment by zuphilip** [comment]
There is a feature request in the upstream Shariff repository for smaller buttons without text: https://github.com/heiseonline/shariff/issues/184 and there is a reference that the Drupal plugin already can do this: https://www.drupal.org/project/shariff
